UI changes
UoA-Discords/website pull request #17
Opened 2022-08-31 23:41 UTC by KwiiHours

- Servers are automatically sorted from most to least liked
- The "like" icon starts grey and becomes red on click
![image](https://user-images.githubusercontent.com/41028518/187607250-080cab33-a0a9-44bb-87dd-b971e2eaf350.png)

- Footer has more spacing, and a new "Not affiliated" disclaimer
![image](https://user-images.githubusercontent.com/41028518/187607236-c46ecda8-cf14-4e66-96c3-39af9a3e73b4.png)

- Small UI elements now go a Discord grey hue on hover, rather than white:
   - Footer links
   - Searchbar search button
   - Tags dropdown chevron 
- Tags dropdown chevron text changed from "More/Less Options" to "Show/Hide Tags" 
![image](https://user-images.githubusercontent.com/41028518/187607263-d609475e-eb22-4fe5-86e9-ffab6792f162.png)

ඞඞ

2022-08-31 23:48 UTC, NachoToast requested changes
LGTM besides 1 tweak.

2022-08-31 23:48 UTC, NachoToast commented on src/redux/slices/entryManager/entryManager.slice.ts
> +    const likes = entries.map((entry) => state.entryManager.entries[entry]?.likes); // get all likes
No need for nullish coalescing here:
```suggestion
    const likes = entries.map((entry) => state.entryManager.entries[entry].likes); // get all likes
```

2022-08-31 23:57 UTC, pumbas600 requested changes
Looking very nice ❤️. I've left a few small suggestions but the main thing is I believe for consistency's sake, you should use `sx={{ }}` when styling MUI components rather than `style={{ }}`. It's basically the same, but things like `paddingTop` and `paddingBottom` can be abbreviated to `pt` and `pb` respectively.

2022-08-31 23:57 UTC, pumbas600 commented on src/components/Footer/Footer.tsx
>                          <span title="This doesn't mean anything, it just looks official.">
I think for consistency's sake, you should add this to the MUI styling, which would be `sx={{ pl: 1, pr: 1, pt: 15 }}` and the same for the bottom padding. (Although I think 1 unit in MUI is like 4px? (I may be mistaken) so you may need to change the value.

2022-08-31 23:57 UTC, pumbas600 commented on src/redux/slices/entryManager/entryManager.slice.ts
> +    const sortedEntries = entries.sort((a, b) =>
`state.entryManager.visibleEntries` is already a list, so you don't need to call `Object.values`. I.e. it can just be 
```ts
const entries = state.entryManager.visibleEntries;
```

You can then also use the non-null insertion operator (`!`) when accessing the entries as we know that the visible entry keys will be present:
```ts
 const likes = entries.map((entry) => state.entryManager.entries[entry]!.likes);
 ```
 I think this might be slightly clearer as using `?.` implies that it possibly might not exist, which is not the case.

2022-08-31 23:57 UTC, pumbas600 commented on src/redux/slices/entryManager/entryManager.slice.ts
> +}
Instead of reversing the array at the end, you can swap the difference in the likes:
```ts
likes[entries.indexOf(b)] - likes[entries.indexOf(a)]);
```

2022-09-01 00:00 UTC, NachoToast commented on src/redux/slices/entryManager/entryManager.slice.ts
> +    const sortedEntries = entries.sort((a, b) =>
We're actually removing the typechecking rule for unchecked index access, so no operator will be needed, `?` or `!`.

2022-09-01 00:06 UTC, pumbas600 commented on src/redux/slices/entryManager/entryManager.slice.ts
> +    const sortedEntries = entries.sort((a, b) =>
Ah, that's good to know :)

2022-09-01 00:22 UTC, pumbas600 requested changes
Sorry to be a pain, but do you mind also changing your use of `style` to `sx` for the other areas where you used it. I've highlighted them to make it easier for you to find them :)

2022-09-01 00:22 UTC, pumbas600 commented on src/components/Pages/Home/ServerCard.tsx
>                      >
Here :)

2022-09-01 00:22 UTC, pumbas600 commented on src/components/SearchBar/SearchBar.tsx
>                                  <SearchIcon />
Here

2022-09-01 00:22 UTC, pumbas600 commented on src/components/SearchBar/SearchBar.tsx
>                      >
Here

2022-09-01 00:33 UTC, pumbas600 commented
>  since style is already used in ~100 places around the site.

Ahh, I didn't realise it was used in other places around the website, probably not too big of a deal then. What do you think @NachoToast?

2022-09-01 00:55 UTC, NachoToast commented
SX whenever possible, however SX is only a prop on MUI components. Style as a fallback, AKA when styling a non-MUI component or using a value not supported by SX props.

2022-09-01 01:07 UTC, KwiiHours commented
I only have one `style` left, which doesn't seem to work when I change to `sx`.

2022-09-01 01:12 UTC, NachoToast approved these changes

2022-09-01 01:12 UTC, NachoToast commented on src/redux/slices/entryManager/entryManager.slice.ts
> +    return sortedEntries; // invert the array so the most liked entries are at the top, and return
Don't forget to remove this comment.

2022-09-01 01:27 UTC, pumbas600 approved these changes
LGTM ❤️

2022-09-01 01:30 UTC, NachoToast commented
Now surely review https://github.com/UoA-Discords/shared/pull/1 😆

2022-09-01 01:47 UTC, merged